# Generated by Django 3.2.13 on 2022-07-22 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('CategoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Estado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CursoId', models.IntegerField(default=0)),
                ('IdCliente', models.IntegerField(default=0)),
                ('Fecha', models.CharField(max_length=20)),
                ('Resumen', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('EId', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(null=True, upload_to='images/personal')),
                ('NombreE', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Especialidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('CursoId', models.AutoField(primary_key=True, serialize=False)),
                ('Imagen', models.ImageField(null=True, upload_to='images/curso')),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=50)),
                ('Costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Estado', models.BooleanField()),
                ('CategoriaID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.categorias')),
            ],
        ),
    ]
