# Generated by Django 3.2.13 on 2022-07-23 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perfilId', models.IntegerField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('image', models.ImageField(null=True, upload_to='images/perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
